zilverline/sequent

lib/sequent/core/helpers/param_support.rb

`.from_params` is already a constructor, just like `.new`, so give it
its own overrideable `#initialize`, simply called `#from_params`.

Give `.from_params` an overrideable constructor

---

README.md
lib/sequent/core/base_event_handler.rb
lib/sequent/core/helpers/self_applier.rb
lib/sequent/core/record_sessions/replay_events_session.rb
lib/sequent/core/workflow.rb

Add specific event handlers for projections and workflows. A workflow allows to execute new commands and a projector alters the projections.

Add workflows and projectors

---

README.md
lib/sequent/core/workflow.rb
lib/sequent/test/event_handler_helpers.rb
spec/lib/sequent/core/workflow_spec.rb

Provide some spec helpers for testing workflows.
Also fix kind of an important bug in `Workflow`.

Workflow spec helpers

---

lib/sequent/core/helpers/param_support.rb
spec/lib/sequent/core/helpers/param_support_spec.rb

This commit also enables parsing array(Integer) and other simple types.
Furthermore the as_params, used mostly in specs, now also creates
similar hashes for posting as your browser would do.

Extend support for parsing arrays from params hash

---

lib/sequent/core/record_sessions/replay_events_session.rb

The bug was that only one record was being saved per aggregate_id. This
makes no sense.

Fix auto-index on aggregate_id

---

lib/sequent/migrations/migrate_events.rb
spec/lib/sequent/migrations/migrate_events_spec.rb

For instance handy for printing to console when migrating.

Add current version to migrate after hook

---

lib/sequent/support/view_projection.rb

Event migrations can cause events to be inserted in existing event
streams. When replaying events by their event ID causes these events to
be replayed at the end of the stream.
This patch changes the order of events for replay to the ID of the
stream and within a stream the event's sequence number. In most
situations the result should be identical. In cases where not, the
sequence number ordering is what you'd expect (since this is also how
Sequent loads an aggregate from the event store).

Order events for replay by stream and sequence

---

lib/sequent/core/record_sessions/replay_events_session.rb

http://www.rubydoc.info/gems/pg/PG/Connection#copy_data-instance_method

Use conn.copy_data

---

lib/sequent/core/record_sessions/replay_events_session.rb

Speed up replay with factor 10

---

lib/sequent/core/event_store.rb
lib/sequent/core/record_sessions/active_record_session.rb
lib/sequent/core/record_sessions/replay_events_session.rb
lib/sequent/support/view_projection.rb
sequent.gemspec
spec/lib/sequent/core/event_store_spec.rb

Support replaying events from a database cursor

Replay from cursor

---

lib/sequent/core/record_sessions/replay_events_session.rb

Problem: when updating a record, using the replay session, the index wasn't being updated as well.
This caused problems when later trying to find a record based on the updated attribute (if that attribute was indexed). This is especially likely to have happened if using `update_all_records` or `delete_all_records`.

Update replay session indexes when updating a record

---

lib/sequent/core/ext/ext.rb
lib/sequent/core/helpers/param_support.rb
lib/sequent/core/helpers/string_to_value_parsers.rb
lib/sequent/core/helpers/value_validators.rb
spec/lib/sequent/core/helpers/attribute_support_spec.rb
spec/lib/sequent/core/helpers/param_support_spec.rb
spec/lib/sequent/core/helpers/type_conversion_support_spec.rb

Breaking change: Date string using from_params must now be in iso8601 format.
Ping @bjpbakker @s0meone

Handle Date in params

---

README.md

I found the README near-impossible to read without source highlighting.  This PR adds that.

Add highlighting to ruby blocks

---

CHANGELOG.md
README.md
lib/version.rb

New release

---

docs/docs/getting-started.md

Add setting up test db

---

.travis.yml
lib/sequent/support/database.rb
sequent.gemspec

Add support for AR 5.2

---

README.md
docs/_data/navigation.yml
docs/docs/building-a-web-application.md
docs/docs/modelling-the-domain.md
lib/sequent/generator/template_project/spec/spec_helper.rb

Guide: "Modelling the domain"

---

docs/_config.yml
docs/_data/navigation.yml
docs/docs/concepts/aggregate-root.md
docs/docs/concepts/command.md
docs/docs/concepts/event.md
docs/docs/concepts/event_store.md
docs/docs/concepts/snapshotting.md

Fixes https://github.com/zilverline/sequent/issues/145 and https://github.com/zilverline/sequent/issues/146

Doc improvements

---

docs/docs/concepts/migrations.md

If you just want to make this change yourselves, that's all good by me.  Just using this as a means to point it out.

Fix spelling

---

lib/sequent/core/transactions/no_transactions.rb

Clarify intent of NoTransactions

Add comment to clarify intent of NoTransactions

---

docs/docs/modelling-the-domain.md

Issue described in https://github.com/zilverline/sequent/issues/175

Fixing issue 175

---

docs/docs/building-a-web-application.md
docs/docs/modelling-the-domain.md

Fixing https://github.com/zilverline/sequent/issues/179

Fixing docs 179

---

docs/docs/getting-started.md
lib/sequent/core/helpers/value_validators.rb

Minor cleanups

---

docs/docs/modelling-the-domain.md

I'm just learning Sequent, so this may not make any sense! :)
Towards the end of this chapter, the reader has implemented behaviour for the _it ignores case in usernames_ example, and all tests pass. But then the reader does some refactoring, and unless they also update `post_command_handler_spec.rb` (is this a deliberate exercise?), they'll finish the chapter with failing tests.
I've updated the guide to first update the test, and then do the refactoring, guideded by the tests. This is how I'd do it, and seems somewhat in keeping with the guide's earlier test-driven approach.
One issue doing it this way, is that the tests all pass _before_ the refactoring is complete, which was a surprise.
Given these expectations:
```ruby
then_events(
PostAuthorChanged.new(
aggregate_id: aggregate_id, …
```

End Modelling the Domain with passing tests

---

.travis.yml
CHANGELOG.md
docs/docs/concepts/migrations.md
docs/docs/getting-started.md
docs/index.md
lib/sequent/core/projector.rb
lib/sequent/migrations/executor.rb
lib/sequent/migrations/functions.rb
lib/sequent/migrations/migrations.rb
lib/sequent/migrations/planner.rb
lib/sequent/migrations/projectors.rb
lib/sequent/migrations/sql.rb
lib/sequent/migrations/view_schema.rb
lib/sequent/sequent.rb
sequent.gemspec
spec/fixtures/db/1/classes.rb
spec/fixtures/db/1/item_records.sql
spec/fixtures/db/1/line_item_records.sql
spec/fixtures/db/2/account_records_2.sql
spec/fixtures/db/2/account_records_3.sql
spec/fixtures/db/2/message_records_2.sql
spec/lib/sequent/fixtures/spec_migrations.rb
spec/lib/sequent/migrations/planner_spec.rb
spec/lib/sequent/migrations/view_schema_spec.rb
spec/spec_helper.rb

Introduce alter table without replaying

---

docs/docs/concepts/aggregate-repository.md

Document usage of AggregateRepository outside CommandService

---

lib/sequent/support/database.rb

Quote the username so it is not uncased

---

docs/_data/navigation.yml
docs/docs/rails-sequent.md
docs/index.md

Add documentation on how to use Sequent in a Rails application.
Helps with #205

Add Rails & Sequent guide

---

docs/docs/concepts/command-service.md
lib/sequent/core/aggregate_repository.rb
lib/sequent/core/command.rb
lib/sequent/core/command_service.rb
lib/sequent/core/event_publisher.rb
lib/sequent/core/event_store.rb
lib/sequent/core/helpers/attribute_support.rb
lib/sequent/core/helpers/mergable.rb
spec/lib/sequent/core/command_service_spec.rb
spec/lib/sequent/fixtures/commands_and_events.rb

Fixes https://github.com/zilverline/sequent/issues/221

Clarify publishing events

---

.travis.yml
sequent.gemspec

See https://travis-ci.org/github/zilverline/sequent/builds/660057278

AR >= 6.0.3 seems to break the build

---

lib/sequent/core/aggregate_repository.rb
spec/lib/sequent/core/aggregate_repository_spec.rb

This reverts commit 3e196b3d0aad72d520711c1600768207bdedcab4.
Need to implement this by checking for stream and events

Revert "Make implementation contains_aggregate same as load_aggregate"

---

docs/docs/building-a-web-application.md

A few more updates on the documentation, no big deal, overall everything is really good 👌

Improvements on Building a web application documentation

---

lib/notices.rb
lib/sequent/configuration.rb

And remove deprecation warning.

Give `database_schema_directory` its own default

---

lib/sequent/core/persistors/replay_optimized_postgres_persistor.rb
spec/lib/sequent/core/persistors/replay_optimized_postgres_persistor_spec.rb

Two improvements:
1. The order of the columns in the indexes no longer matters
2. The type of the column in the where and index
(String or Symbol) no longer matters. Internally everything
is stored as String.
For now on if you define an Index like:
```
{FooRecord => [[:aggregate_id, :tenant_id]]}
```
All queries below will hit the Index:
```
{aggregate_id: 1, tenant_id: 2}
{'aggregate_id' => 1, 'tenant_id' => 2}
{'tenant_id' => 2, 'aggregate_id' => 1}
```

Improve ReplayOptimizedPostgresPersistor::Index

---

docs/docs/rails-sequent.md

Do not set `database_config_directory` twice.
Mentioned in #259

Fix documentation

---

.github/workflows/rspec.yml
lib/sequent/support/database.rb
spec/lib/sequent/support/database_spec.rb

See https://github.com/zilverline/sequent/pull/277.

Fix private method call to resolve_config_for_connection

---

docs/docs/concepts/aggregate-repository.md
docs/docs/concepts/aggregate-root.md
docs/docs/concepts/types.md

Fix few typos in docs

---

.github/workflows/rspec.yml
sequent.gemspec

bump AR version

---

sequent.gemspec

Allow update active_star to latest patch

---

lib/sequent/test/command_handler_helpers.rb

Update doc for command handler helper

---

docs/docs/concepts.md
docs/docs/concepts/gdpr.md

Fixes https://github.com/zilverline/sequent/issues/222

Add first version of GDPR information

---

lib/sequent/migrations/view_schema.rb
lib/sequent/test/database_helpers.rb

- Allow maintain_test_database_schema usage for development as well
- Fix replay_all! and allow to pass group_exponent as param

improve maintain test schema

---

.github/workflows/rspec.yml

Also upgrade ar version in build matrix.

Add ruby 3.2 to build matrix

---

sequent.gemspec

Hello ! It's blocking me to update others gems :) It's also useful for ruby 3.2

Bump parser dependency

---

docs/docs/concepts/advanced.md

Clarifies and closes https://github.com/zilverline/sequent/issues/379

Improve upcasting docs

---

integration-specs/simple/spec/app_spec.rb
lib/sequent/configuration.rb

For applications running outside Rails but with monkeypatched Rails module.

Improve check for running in Rails

---

lib/sequent/core/helpers/message_handler.rb

Fixes https://github.com/zilverline/sequent/issues/411

Fix debugging message handling

---

bin/sequent
docs/docs/upgrade-guide.md

- **Improve text on upgrade command**
- **Suggest `--conservative` instead of `--source`.**

sequent 8 upgrade improvements

---

lib/sequent/generator/template_project/spec/spec_helper.rb

Avoids a `[projector]_records` table exists error when running specs for the second time. Implemented by dropping and re-creating the event store and view schemas before running a test suite.

Clear the database before running a test suite
