lib/sequent/core/command.rb
lib/sequent/core/command_record.rb
lib/sequent/core/core.rb
lib/sequent/core/event.rb
lib/sequent/core/event_record.rb
lib/sequent/core/event_store.rb
lib/sequent/core/helpers/association_validator.rb
lib/sequent/core/helpers/attribute_support.rb
lib/sequent/core/helpers/param_support.rb
lib/sequent/core/helpers/type_conversion_support.rb
lib/sequent/core/sequent_oj.rb
lib/sequent/core/value_object.rb
lib/sequent/sequent.rb
lib/sequent/test/command_handler_helpers.rb
spec/lib/sequent/core/event_spec.rb
spec/lib/sequent/core/serializes_command_spec.rb
spec/lib/sequent/core/serializes_event_spec.rb
spec/lib/sequent/core/value_object_spec.rb

Test serializing > 500.000 events to_json:
With to_json: [68921] ms
With oj: [21171 ms]
Removing ActiveSupport::JSON completely as a result calling `valid?` on a `Command` or `ValueObject` will not result in serialized `errors` and `validation_context` attributes.
```
person = Person.new(name: "Kim")
person.valid?
Sequent::Core::Oj.dump(person)
=> "{\"name\":null,\"validation_context\":null,\"errors\":{}}"
Sequent::Core::Oj.dump(person.attributes)
=> "{\"name\":null}"
```
Both `EventRecord` and `CommandRecord` will call `attributes` method on `event` and `command` before persisting.

Performance improvement when using oj instead of to_json

---

lib/sequent/test/command_handler_helpers.rb

I've migrated the 'then_events' in command_handler_helpers to use the latest rspec syntax 'cause I was getting the annoying warning running my own test.

Migrated to latest rspec syntax

---

lib/sequent/test/command_handler_helpers.rb

Automatically determine the associated event stream information by
looking at the event handlers defined in the aggregate roots. This
allows the old test syntax to be used when defining test scenarios.

Restore old `given_events` API

---

lib/sequent/core/base_command_handler.rb

By default `BaseCommandHandler#handles_message?` returns whether a
command is registered with the `on` DSL syntax of `SelfApplier`.

Default `handles_message?` implementation

---

lib/sequent/core/aggregate_root.rb

If a `HashWithIndifferentAccess` is passed, merging it into a regular hash
will change semantics. Now `merge` is called on the passed-in hash.
Also, it's a bit safer to eliminate possible overrides of `aggregate_id`
and `sequence_number`.

Preserve hash implementation when merging

---

lib/sequent/core/helpers/attribute_support.rb
spec/lib/sequent/core/helpers/attribute_support_spec.rb

Updating an object with attribute support will return a new instance of
such object with the given changes merged in.

Support `update` on attribute support

---

lib/sequent/test/command_handler_helpers.rb

Spec helpers `given_events` and `then_events` now can use both varargs and a list of events.
Also any unhandled errors are raised after a spec.

Spec helper improvements

---

spec/lib/sequent/core/aggregate_repository_spec.rb
spec/lib/sequent/core/helpers/type_conversion_support_spec.rb

Fixes these kind of warnings:
> WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /Users/daniel/Development/Workspaces/code/sequent/spec/lib/sequent/core/aggregate_repository_spec.rb:91:in `block (2 levels) in <top (required)>'.

Fix warnings about `raise_exception` in specs

---

README.md
lib/sequent/sequent.rb
lib/sequent/test.rb
lib/sequent/test/event_stream_helpers.rb
lib/sequent/test/test.rb

Including test documentation in the README.
```
##
#
#
#
#
#
#
#
#
#
#
```

Add EventStreamHelpers

---

.gitignore
lib/sequent/core/event_store.rb
spec/lib/sequent/core/event_store_spec.rb

Before StreamRecord existed the EvenStore raised an AggregateNotFound when it was not found in the EventStore.

Do not raise ActiveRecord::RecordNotFound

---

lib/sequent/test/command_handler_helpers.rb

The then_fails_with limits the options of checking the raised exception (only on class). 
Also we want to avoid Death-By-DSL. For instance rspec alreay provides a nice way to check for exceptions.

Remove dsl for exception checking

---

lib/sequent/core/helpers/association_validator.rb
lib/sequent/core/helpers/attribute_support.rb
spec/lib/sequent/core/helpers/association_validator_spec.rb
spec/lib/sequent/core/helpers/attribute_support_spec.rb

Introduce error reporting for each individual item in an array. Current limitation is that the individual item in the array should be a `Sequent::Core::ValueObject`. Later we can add "simple" types as `Integer`, `DateTime` etc

Report error for all items in array

---

lib/sequent/test/time_comparison.rb
spec/lib/sequent/test/time_comparison_spec.rb

This patch on `Time`, `DateTime` and `ActiveSupport::TimeWithZone` omits nanosecond difference when comparing times. 
Allows you to keep using built-in rspec matchers (such as `eq`) without having to worry about nanosecond differences which are likely to occur when running on a Linux machine or when time objects have been serialized (ie. Postgres) and lost subsecond precision.
Usage:
Just `require 'sequent/test/time_comparision'` in your spec file (or spec_helper.rb), and you're good to go.

Add test helper (patch) for datetime comparisons

---

README.md
lib/sequent/configuration.rb
lib/sequent/rake/tasks.rb
lib/sequent/support.rb
lib/sequent/support/base_view_model.rb
lib/sequent/support/database.rb
lib/sequent/support/view_projection.rb
lib/sequent/support/view_schema.rb
spec/lib/sequent/support/database_spec.rb

Make Sequent setup a bit less intrusive with some rake tasks to create and maintain the database and the required schemas (for the event store and the view projections).

Provide Rake tasks to ease setup

---

lib/sequent/core/record_sessions/replay_events_session.rb

replay of production data: `278.2s` with master, and `282.8s` with this change.

Support exotic column types by always casting

---

lib/sequent/core/helpers/array_with_type.rb
lib/sequent/core/helpers/association_validator.rb
lib/sequent/core/helpers/param_support.rb
spec/lib/sequent/core/helpers/association_validator_spec.rb
spec/lib/sequent/core/helpers/param_support_spec.rb

Delegate the type checking for array types to the association validator,
while type checking the elements of the array in param support (similar
to any other param).

Fix type checking array params in `from_params`

---

lib/sequent/core/helpers/param_support.rb
spec/lib/sequent/core/helpers/param_support_spec.rb

Values like `false`, `[]`, `''` are `blank` according to ActiveRecord.
Though these represent actual values that you need to deal with. In
params there's a difference between not-present and blank values. Some
of them might be dealt with in the same way (e.g. the params are
invalid), others might be actual values (like false for a Boolean).

Fix reading 'blank' values from params

---

lib/sequent/core/event_record.rb
lib/sequent/core/event_store.rb
lib/sequent/core/helpers/attribute_support.rb

Previously `event.attributes` was used to serialise events. 
Due to this it was not really possible to change the way an object is
serialised to and from JSON.
By introducing `as_json` explicitly for serialising this option becomes
available.

Change serialising of events to use as_json directly

---

lib/sequent/core/event_store.rb

Instead of only receiving an implicit conversion error,
this also adds the actual event that caused that error.

Add specific error in case event_json is messed up

---

lib/sequent/test/command_handler_helpers.rb
lib/sequent/test/event_handler_helpers.rb

Now you can test your events like this:
```
event1 = Event.new
event3 = Event.new
then_events event1, OtherEvent, event3
```
Then Sequent will check that the resulting events are of type `[Event,
OtherEvent, Event]`, and will also check the attributes of `event1` and
`event3` against the first and third events.

Improve `then_events`.

---

lib/sequent/core/helpers/association_validator.rb
lib/sequent/core/helpers/attribute_support.rb
spec/lib/sequent/core/helpers/association_validator_spec.rb

Include the superclass' types when finding the `type_for` an attribute.

Fix validation of inherited array properties

---

lib/sequent/core/aggregate_repository.rb

Extend 'Exception' for exceptions, unexpected external factors; network
down, out of memory etc.  Extend 'StandardError' to signal application
level errors.
Ruby's 'rescue', without supplying an exception type, will catch
'StandardError' and children.  Exceptions extending 'Exception' will
need to be stated in the rescue statement making it very hard for
frameworks supply 'recue_from' like features.

Extend StandardError instead of Exception

---

lib/sequent/core/event_store.rb

This will impact your app if you are handling `ActiveRecord::RecordNotUnique` originating from the event store.
@bjpbakker @s0meone @erikrozendaal comments?

Wrap ActiveRecord::RecordNotUnique with Sequent::Core::EventStore::OptimisticLockingError

---

lib/sequent/core/event_store.rb
spec/lib/sequent/core/event_store_spec.rb

When a command can result in multiple events inserting
each event_record separately can become slow.
By using 
insert into (..) values (..),(..),(..)
we save roundtrips to the database.
Possible downside is that when an ActiveRecord::RecordNotUnique
is thrown we no longer know which event caused the error.

Insert all events per commit in a single statement

---

lib/sequent/core/helpers/string_to_value_parsers.rb
spec/lib/sequent/core/command_service_spec.rb

We register validates_numericality_of when using Integer
The value ’09’ is considered numerical but is not a valid Integer 
according to Integer(’09’). So we strip leading zeros since they have
no meaning in Integers.

Remove leading zeros from Integer values

---

lib/sequent/test/event_handler_helpers.rb

Executes commands should be valid. Since `then_commands` is a test helper that asserts the attributes of recorded commands (using an internal recorder setup), it should validate that executed commands are valid, too.

`then_commands` asserts that commands are valid

---

lib/sequent/core/command.rb
spec/lib/sequent/core/command_spec.rb

Sequent::Core::Commands
This avoids the use of `String#constantize` when you want to find a
command from a string. The syntax is
`Sequent::Core::Commands.find(string)`.

Register subclasses of Sequent::Core::Command with

---

lib/sequent/core/event_store.rb
lib/sequent/migrations/migrate_events.rb
spec/lib/sequent/core/event_store_spec.rb
spec/lib/sequent/migrations/migrate_events_spec.rb

Enable projects to replay events without downtime. The strategy is as follows:
1) Create new view schema
2) Replay all events
3) When done put the app in maintenance mode (this is only for a short time)
4) Replay events not yet replayed
5) Switch view schema
6) Restart your app
To keep track of events not yet replayed the `on_progress` block is passed in the ids of the
events replayed. The app that is deployed needs to keep track of these ids so in step 4 you can select all events `where id not in (replayed_ids)`.

Nodowntime replay

---

lib/sequent/core/transactions/active_record_transaction_provider.rb

Read:
http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html
Without this change, there is a potential bug:
```ruby
ActiveRecord::Base.transaction do
Sequent.configuration.command_service.execute_commands command
end
on Command do
do.some.things
fail ActiveRecord::Rollback
end
```
In this example, you might be surprised to find that `do.some.things`
does not get rolled back! This is because AR doesn't automatically make
a "savepoint" for us when we call `.transaction` in a nested manner. In
order to enable this behaviour, we have to call `.transaction` like
this: `.transaction(requires_new: true)`.

Always require a new transaction.

---

lib/sequent/core/event_store.rb

Instead of replaying one event to all event handlers, and then moving on
to the next event. This caused a bug in workflows:
Say you append a number of events to an aggregate. The first of these
events triggers a workflow, which appends some extra events. These extra
events will be sent *first* to the event handlers, out of order.
To get the correct order of events being applied, it's still important to
always have workflows lower in the event_handlers list than projectors.

Play all events per-event handler.

---

lib/sequent/core/record_sessions/replay_events_session.rb
spec/lib/sequent/core/record_sessions/replay_events_session_spec.rb

It was possible to have clashes in indexed records when:
- having multiple indices on the same record;
- with the same number of indexed columns
- that could have the same value
For example:
An indexed record FooRecord with the following indices:
FooRecord => [[:id, :val_1], [:id, :val_2]]
This was internally indexed with the key:
[FooRecord, record[:id], record[:val_1]]
and
[FooRecord, record[:id], record[:val_2]]
If val_1 and val_2 had the same value it used the same index key
resulting in unwanted behaviour (or view projection mayhem).
By adding the column names to the indexed key this now is truly unique:
[FooRecord, :id, record[:id], :val_1, record[:val_1]]
and
[FooRecord, :id, record[:id], :val_2, record[:val_2]]

Add column names to index key to avoid clashes

---

lib/sequent/core/aggregate_snapshotter.rb
lib/sequent/core/base_command_handler.rb
lib/sequent/core/command_service.rb
lib/sequent/core/helpers/self_applier.rb
lib/sequent/test/command_handler_helpers.rb
spec/lib/sequent/core/command_service_spec.rb

I have added this because it's a convenient interface that I can
overwrite when my own implementation of `.handle_message` differs.
It's similar to `.method_missing` and `.respond_to?`.

Add `.handles_message?` method

---

bin/sequent
sequent.gemspec

Add ‘parser’ as dependency otherwise the generator does not work.
First check arguments are present before further parsing of generator commands.
Fixes https://github.com/zilverline/sequent/issues/140

Fix sequent generators

---

lib/sequent/core/aggregate_root.rb
lib/sequent/core/helpers/autoset_attributes.rb
spec/lib/sequent/core/aggregate_root_spec.rb
spec/lib/sequent/core/fixtures.rb

This PR adds two features:
1. `apply_if_changed`
In some cases you only want to apply an event if the relevant state changed. For instance if you call
```ruby
person.set_name('ben')
person.set_name('ben')
```
you may want to only apply `set_name` once. For this scenario you had to implement this yourself like:
```ruby
class Person < Sequent::AggregateRoot
def set_name(name)
apply NameSet, name: name unless @name == name
end
on NameSet do |event|
@name = event.name
end
end
```
With `apply_if_changed` you can use: `apply_if_changed, NameSet, name: name`
2. Add `autoset_attributes_for_events`
This will register event handlers for all relevant events for which you just want to capture the defined `attrs` in the AggregateRoots state.
With this we can re-write the above example as:
```ruby …
```

Add apply if changed

---

lib/sequent/core/helpers/message_handler.rb
spec/lib/sequent/core/helpers/message_handler_spec.rb

It was possible to register multiple handler blocks for a single ‘message’.
However only the last one registered was executed since if was
overriding the previous one registered.
So the desired behavior is to actually execute all the registered
handlers.

Handle all registered handler in a MessageHandler

---

lib/sequent/configuration.rb

This is what is expected, so enable by default

Enable transactions by default

---

docs/docs/concepts/types.md
lib/sequent/core/command.rb
lib/sequent/core/helpers/default_validators.rb
lib/sequent/core/helpers/secret.rb
lib/sequent/core/helpers/string_to_value_parsers.rb
sequent.gemspec
spec/lib/sequent/core/command_service_spec.rb
spec/lib/sequent/core/helpers/secret_spec.rb

Secrets can be used to encrypt values in Commands so its value
is never stored in plain text in the command_records table
in the database.

Add Sequent::Secret as a Type

---

docs/docs/concepts/types.md
lib/sequent/core/ext/ext.rb
lib/sequent/core/helpers/string_to_value_parsers.rb
lib/sequent/core/helpers/value_validators.rb
spec/lib/sequent/core/event_spec.rb
spec/lib/sequent/core/helpers/string_validator_spec.rb

We allowed anything that could be `to_s`-ed in the past.
To not break existing events `to_s` all the input so it is really a String

Be backward compatible with type String

---

lib/sequent/core/ext/ext.rb
lib/sequent/core/helpers/string_to_value_parsers.rb
spec/lib/sequent/core/helpers/type_conversion_support_spec.rb

I'm using Sequent with ruby 2.6.x and I get some deprecation warnings:
```
warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
```
I think I fixed all occurrences.

BigDecimal.new is deprecated in ruby 2.6

---

docs/docs/concepts/workflow.md
lib/sequent/core/transactions/active_record_transaction_provider.rb
lib/sequent/core/workflow.rb
lib/sequent/test/event_handler_helpers.rb
spec/lib/sequent/core/workflow_spec.rb

As discussed in #168 , I created a helper to let a Workflow run side effects after a transaction commits. I also documented the feature.
It is basically used like this:
```ruby
class SendEmailWorkflow < Sequent::Workflow
on UserCreated do |event|
after_commit do
end
end
end
```
closes #168

Add `after_commit` to workflows

---

docs/docs/concepts/configuration.md
lib/sequent/configuration.rb
lib/sequent/core/event_record.rb
lib/sequent/core/event_store.rb
spec/lib/sequent/core/event_record_spec.rb

First of all, I'd like to thank you for this framework. I'm just getting started with event sourcing and your project and documentation have been a great benefit for me to understand how this all works. Being familiar with ActiveRecord makes this project appealing and `ReplayOptimizedPostgresPersistor` looks awesome.
In my application I'm wanting to add [metadata] and [correlation/causation ids][correlation_causation] to the `event_records` table. I'm introducing this change to take advantage of `SerializesEvent#event=` to remove duplication and also allow a subclass of `EventRecord` to write additional columns from the event.
**Usage**
```ruby
class AppEventRecord < Sequent::Core::EventRecord
def event=(event)
super
self.correlation_id = event.correlation_id if …
```

Event record attributes

---

lib/sequent/core/transactions/active_record_transaction_provider.rb

I'm going to start by saying that I am a bit embarrassed by this. My last pull-request was not sufficiently tested in "real-world" scenario and I quickly came to the realisation that I misunderstood how ActiveRecord's `after_commit` was behaving. Not only it called the block for each operation committed in the transaction, it was not clearing it's queue after the transaction was done.
I changed the ActiveRecordTransactionProvider's `after_commit` implementation to let it manage its hook. There was other solutions, like using [after_transaction_commit](https://github.com/instructure/after_transaction_commit) or [after_commit_everywhere](https://github.com/Envek/after_commit_everywhere) but I did not want to introduce a new dependency to the project. 
If you'd prefer another implementation …

Fix the after_commit hook

---

lib/sequent/core/command_record.rb
lib/version.rb
spec/lib/sequent/core/serializes_command_spec.rb

Some attributes are optional:
- organization_id
- event_aggregate_id
- event_sequence_number
So only set these on the CommandRecord if they are present
in the `Command` and the `CommandRecord`.

Only set existing attributes on `CommandRecord`

---

sequent.gemspec

This changes the version pin from `3.3.x` to `3.x` for the `oj` gem. Looking at the [changelog](https://github.com/ohler55/oj/blob/master/CHANGELOG.md) there are lots of useful bug fixes.
I ran the tests and they all passed:
```
Finished in 58.01 seconds (files took 1.04 seconds to load)
367 examples, 0 failures, 1 pending
```

Allow 3.x versions of oj

---

lib/sequent/core/ext/ext.rb

See #185
In short, it seems like the goals of `Boolean` can be accomplished with it as a module, especially considering that there doesn't seem to be an expectation that `Boolean` will be instantiated. This also makes it more compatible with existing patterns, e.g.
```ruby
module Boolean; end
TrueClass.include Boolean
FalseClass.include Boolean
true.is_a? Boolean # => true
false.is_a? Boolean # => true
```

Make Boolean a module

---

Rakefile
docs/docs/building-a-web-application.md
docs/docs/concepts/projector.md
lib/sequent.rb
lib/sequent/application_record.rb
lib/sequent/core/command_record.rb
lib/sequent/core/event_record.rb
lib/sequent/core/persistors/active_record_persistor.rb
lib/sequent/core/persistors/replay_optimized_postgres_persistor.rb
lib/sequent/core/stream_record.rb
lib/sequent/core/transactions/active_record_transaction_provider.rb
lib/sequent/generator/template_project/app/records/post_record.rb
lib/sequent/migrations/view_schema.rb
lib/sequent/rake/migration_tasks.rb
lib/sequent/rake/tasks.rb
lib/sequent/support/database.rb
spec/fixtures/db/1/classes.rb
spec/lib/sequent/core/persistors/active_record_persistor_spec.rb
spec/lib/sequent/core/persistors/replay_optimized_postgres_persistor_spec.rb
spec/lib/sequent/migrations/view_schema_spec.rb
spec/lib/sequent/support/database_spec.rb
spec/spec_helper.rb

Subclassing `ActiveRecord::Base` allows applications to isolate the connection for sequent, e.g. with a separate schema search path.

Replace ActiveRecord::Base with Sequent::ApplicationRecord

---

CHANGELOG.md
docs/docs/concepts/configuration.md
lib/sequent/configuration.rb
lib/sequent/core/command.rb
lib/sequent/core/event_record.rb
lib/sequent/core/helpers/attribute_support.rb
spec/fixtures/for_attribute_support.rb
spec/lib/sequent/core/aggregate_root_spec.rb
spec/lib/sequent/core/command_service_spec.rb
spec/lib/sequent/core/event_spec.rb
spec/lib/sequent/core/fixtures.rb
spec/lib/sequent/core/helpers/attribute_support_spec.rb
spec/lib/sequent/core/helpers/param_support_spec.rb
spec/lib/sequent/core/value_object_spec.rb
spec/lib/sequent/core/workflow_spec.rb

Right now unspecified attributes will be silently ignored. This PR raises an error if an unknown attr is passed in.
For example when we have some event:
```rb
class SomeEvent < Sequent::Core::Event
attrs message: String
end
```
We instantiate it with unknown attributes:
```rb
SomeEvent.new(message: 'hello', something: 'this should raise', something_else: 'and this')
```
It gives us a nice descriptive error:
```rb
Sequent::Core::Helpers::AttributeSupport::UnknownAttributeError:
SomeEvent does not specify attrs: something, something_else
```
This works on anything that includes `AttributeSupport` like `Command` and `ValueObject`.
Implements #193

Ensure correct attrs

---

lib/sequent/generator/project.rb
spec/lib/sequent/generator/project_spec.rb

When running `sequent new blog-app` it produces
file `blog-app.rb` will contain 
```rb
module Blog-app
end
```
this PR will fix this error

bug fix: allow dash in project name

---

docs/docs/building-a-web-application.md
docs/docs/getting-started.md
docs/docs/modelling-the-domain.md
docs/index.md

Firstly, thanks for providing a helpful documentation to help people to get started.
I've improved the docs a little bit and also fixed the issue #212.
There's more details in the commit messages of this PR.
Hope my changes make sense :)

Update docs (fixes #212)

---

README.md
docs/_data/navigation.yml
docs/docs/concepts/advanced.md
lib/sequent/sequent.rb
lib/sequent/util/dry_run.rb
lib/sequent/util/util.rb
spec/lib/sequent/util/dry_run_spec.rb

When using dry run the given commands and resulting events are not stored
but recorded for inspection purposes.
It will also record which Projectors and Workflows would have been invoked
as a result of the Events applied.
Due to the fact that the Sequent.configuration is a singleton and shared
among Threads dry run is not Thread safe.

Add dry run option

---

docs/docs/rails-sequent.md

I initially just put it into `database.yml` on its own as per the docs and it didn't work.

Adjust the documentation to show that schema_search_path should be nested

---

lib/sequent/generator/template_project/spec/app/projectors/post_projector_spec.rb
lib/sequent/generator/template_project/spec/lib/post/post_command_handler_spec.rb

RSpec automatically loads the `spec` directory into the load paths.
`require_relative`ing the spec_helper isn't necessary as you can just require it.

Remove unnecessary require_relative

---

sequent.gemspec

We actually meant all 6.0.x releases. Fixes https://github.com/zilverline/sequent/issues/227

Fix AR versions in gemspec

---

lib/sequent/core/event_store.rb

When using `connection.insert` ActiveRecord will return the id of the inserted rows.
This results in doing a query in the postgres metadata tables to figure out the
name of the primary key.
So pass in the primary key name to prevent all the metadata queries.

Do not query for pk name of event_records table for each insert

---

sequent.gemspec

**The issue**
When moving to sequent `3.4.0` (https://github.com/zilverline/sequent/commit/8094b3c39ec5869d2a11e93109f8f3f70dc4a492) I noticed sequent fixed `parser`'s version to `2.6.x`. Previously it required `~> 2.5` which would be more permissive to any version below `3`.
This means the gem cannot be installed along with other dependencies that require sequent `2.7`, I'm wondering if we could relax the dependency requirements to minimum 2.6.5 but still allow newer minor versions, or if there is any reason why sequent might not work with newer minor versions?
**How to reproduce**
Noticed this conflict with the latest version of rubocop, you can reproduce it by trying to install both gems:
```
source "https://rubygems.org"
gem "rubocop", "0.84.0"
gem "sequent", "3.5.0"
$ bundle install …
```

Relax `parser` version requirement

---

lib/sequent/core/aggregate_repository.rb
spec/lib/sequent/core/aggregate_repository_spec.rb

In case of gdpr one can choose to delete events from the event store
but keep the eventstreams. This can cause load_aggregate to fail
but contains_aggregate to return true.

Make implementation contains_aggregate same as load_aggregate

---

lib/sequent/core/command_record.rb

SnapshotEvent gets the same sequence_number as the last event, therefor
we need to explicitly exclude them from being a parent of a Command.

Exclude SnapshotEvent as parent of a Command

---

docs/docs/modelling-the-domain.md

I believe the docs is trying to say that the "Next thing we want to do is create a `AuthorCommandHandler`" instead of a `UserCommandHandler`.  It was probably confused with the `Usernames` instance just mentioned on the same paragraph. Please let me know if this fix is correct.

Quick update on Modelling your Domain Docs 

---

CHANGELOG.md
docs/docs/concepts/configuration.md
docs/docs/rails-sequent.md
lib/notices.rb
lib/sequent.rb
lib/sequent/configuration.rb
lib/sequent/rake/migration_tasks.rb
lib/version.rb

This allows the database schema and migration files to be stored in a separate place from the database config files.
This is helpful when embedding Sequent in Ruby on Rails, where the standard approach is for database config to be in `/config` and database schemas and migrations to be in `/db`.

Add a new configuration parameter `database_schema_directory`

---

lib/sequent/core/command_service.rb
lib/sequent/core/transactions/active_record_transaction_provider.rb
lib/sequent/util/skip_if_already_processing.rb
spec/lib/sequent/core/workflow_spec.rb

Reset the re-entry lock after command queue is empty
so when the after_commit queue executes another
command the process command is re-entrant again.
Also make sure that after_commit is a queue and
and the registered blocks are popped otherwise
they will be executed on each new commit.
Fixes #246

Fix re-entry of process_commands in after_commit hook

---

.travis.yml
lib/sequent/migrations/executor.rb
lib/sequent/migrations/view_schema.rb
sequent.gemspec
spec/fixtures/db/1/item_records.sql
spec/fixtures/db/1/line_item_records.sql
spec/fixtures/db/1/message_records.indexes.sql
spec/lib/sequent/core/persistors/active_record_persistor_spec.rb
spec/lib/sequent/core/persistors/replay_optimized_postgres_persistor_spec.rb
spec/lib/sequent/migrations/view_schema_spec.rb
spec/spec_helper.rb

- Split creating indexes from creating tables
- Remove `unique` prefix in index names

split creating indexes from creating tables

---

.github/workflows/rspec.yml
lib/sequent/core/aggregate_root.rb
lib/sequent/core/aggregate_roots.rb
lib/sequent/test/command_handler_helpers.rb

This becomes quite slow when running running specs since
the objectspace will grow during test runs.
Use the same approach as Commands to look for descendants
of AggregateRoot.

Don't use class.descendants to find subclasses

---

lib/sequent/core/aggregate_snapshotter.rb
lib/sequent/rake/migration_tasks.rb

- Run rake task `sequent:snapshots:set_snapshot_threshold` will get `args` missing
- Run ` Sequent::Core::SnapshotCommand` command will get event_store undefined method error in AggregateSnapshotter

FIX: enable snapshot setting errors

---

lib/sequent/core/persistors/replay_optimized_postgres_persistor.rb
spec/lib/sequent/core/persistors/replay_optimized_postgres_persistor_spec.rb

The `data.encoder.encode` was not the solution. This still
returns a non string value and since we use this in csv or
customer prepared statement we need to cast to a string
manually.

Explicitly cast value from_database in optimized replayer

---

lib/sequent/support/database.rb
spec/lib/sequent/support/database_spec.rb

I prefer to use a `DATABASE_URL` env var to set my database config. Many tooling and hosting environments default to such an URL, including HEROKU and AWS-RDS.
The database config can not always deal with it. Several methods, like `drop!` would flunk as they expect the config to have keys like `database` or `username` and such. 
This patch leverages ActiveRecords API to convert any valid Activerecord config hash into a normalized config hash including keys such as `database` or `username`. Which then can be used anywhere we expect config with certain keys.
It does create a HashWithIndifferentAccess, so normalizing the keys to symbols makes it behave a tad more like one expects (and not accidentally creating a key `"database"` next to a key `:database`), so this patch made that apparent by …

Allow database config to be set using a postgres connection URL

---

sequent.gemspec

So it is compatible with the latest rubocop.
Fixes https://github.com/zilverline/sequent/issues/268

Relax parser version

---

lib/sequent/core/persistors/replay_optimized_postgres_persistor.rb
spec/lib/sequent/core/persistors/replay_optimized_postgres_persistor_spec.rb

This needed a small refactor due to introduction of rubocop
but noticed a spec was missing that asserted the buffer was read
until empty.

Add spec that asserts optimized postgres persistor keeps on reading

---

lib/sequent/support/database.rb

Default config as provided by `sequent new blog` will use aliases, and
many people familiar with Rails' database.yml will use aliases too.
This fixes #289

Allow aliases when loading the database YML config.

---

lib/sequent/core/command_record.rb
spec/lib/sequent/core/command_record_spec.rb

There is a bug with `Sequent::Core::CommandRecord.last.command`.
It will fail with `wrong constant name` if you have a class with a namespace, for example: `Foo::Bar`
I believe it happens because Class.const_get should accept string instead of symbol

command_record.command producing wrong constant name exception

---

docs/docs/concepts/aggregate-repository.md

Update docs to use `load_aggregates` instead of `load_aggregate` for loading multiple aggregates in a single call. More info at the following issue: https://github.com/zilverline/sequent/issues/320

Update aggregate-repository.md docs

---

docs/docs/concepts/advanced.md
lib/sequent/core/helpers/message_handler.rb
lib/sequent/core/helpers/message_handler_option_registry.rb
lib/sequent/core/helpers/message_router.rb
lib/sequent/core/workflow.rb
spec/lib/sequent/core/helpers/message_handler_option_registry_spec.rb
spec/lib/sequent/core/helpers/message_handler_spec.rb

Example usage:
```ruby
class MyEventHandler
include Sequent::Core::Helpers::MessageHandler
option :my_option do |matcher, argument|
argument == :my_value # true
end
on MyEvent, my_option: :my_value do |event|
end
end
```
Can be useful for cases like this:
```ruby
module DeduplicableWorkflow
extend ActiveSupport::Concern
included do
option :deduplicate_on do |matcher, attributes|
end
end
end
class BaseWorkflow < Sequent::Workflow
include DeduplicableWorkflow
end
class MyWorkflow < BaseWorkflow
on MyEvent, deduplicate_on: %i[aggregate_id] do |event|
end  
end
```
Registered options are scoped per class hierarchy, some in the above example, all workflows extending from `BaseWorkflow` support the `deduplicate_on` option in `on` definitions. Classes in other hierarchies (like a …

Introducing: message handler options

---

docs/docs/concepts/advanced.md
lib/sequent/core/helpers/attr_matchers/argument_serializer.rb
lib/sequent/core/helpers/attr_matchers/equals.rb
lib/sequent/core/helpers/attr_matchers/greater_than.rb
lib/sequent/core/helpers/attr_matchers/greater_than_equals.rb
lib/sequent/core/helpers/attr_matchers/less_than.rb
lib/sequent/core/helpers/attr_matchers/less_than_equals.rb
lib/sequent/core/helpers/attr_matchers/not_equals.rb
lib/sequent/core/helpers/message_matchers/any.rb
lib/sequent/core/helpers/message_matchers/argument_serializer.rb
lib/sequent/core/helpers/message_matchers/has_attrs.rb
lib/sequent/core/helpers/message_matchers/instance_of.rb
lib/sequent/core/helpers/message_matchers/is_a.rb
spec/lib/sequent/core/helpers/attr_matchers/equals_spec.rb
spec/lib/sequent/core/helpers/attr_matchers/greater_than_equals_spec.rb
spec/lib/sequent/core/helpers/attr_matchers/greater_than_spec.rb
spec/lib/sequent/core/helpers/attr_matchers/less_than_equals_spec.rb
spec/lib/sequent/core/helpers/attr_matchers/less_than_spec.rb
spec/lib/sequent/core/helpers/attr_matchers/not_equals_spec.rb
spec/lib/sequent/core/helpers/message_matchers/any_spec.rb
spec/lib/sequent/core/helpers/message_matchers/has_attrs_spec.rb

In order to simplify the interface for message/attr matchers.

Rename `matcher_description` to `to_s`

---

docs/docs/building-a-web-application.md

This is related to my prior [PR](https://github.com/zilverline/sequent/pull/329)
This is technically not something that happens within sequent but a useful note for those following the tutorial/ building apps with multiple databases.

Add a note to clear db connections for each role if using multiple

---

CHANGELOG.md
lib/sequent/test.rb
lib/sequent/test/workflow_helpers.rb
spec/lib/sequent/core/workflow_spec.rb
spec/lib/sequent/test/test_spec.rb

Using WorkflowHelpers could potentially and most likely break other specs
running after any spec including WorkflowHelpers. This was due to the fact
this spec altered the Sequent.configuration without restoring its original value.
To ensure this WorkflowHelpers plays nicely with other specs you
must, as of now, include it using `workflows: true` metadata:
```ruby
RSpec.configure do |config|
config.include Sequent::Test::WorkflowHelpers, workflows: true
end
```

Fix conflict when using Sequent::Test::WorkflowHelpers

---

lib/sequent/core/command.rb
spec/lib/sequent/core/command_spec.rb

Define callback `after_initialize` in `Sequent::Command`. We can use this callback to do more things, such as set default value for command attributes.
```ruby
class AfterInitCommand < Sequent::Command
attrs flag: Boolean
after_initialize do
@flag = true if @flag.nil?
end
end
```

[feature] define after_initialize callback in sequent command

---

docs/docs/rails-sequent.md
lib/sequent/rake/migration_tasks.rb

The problem occurs when rails migrations are run after the view_schema and sequent_schema
are created and the migrations run when `schema_search_path` is set to contain both
the active record schema as well and the sequent schema's.
To get around this one must wrap `rails db:migrate` with a custom task in order to
set the `schema_search_path` to only contain the active record schema.
A better way would be to prepend something to `Rake::Task['db:migrate']` but there is only
`enchance` which will add a task as last one of the prerequisites.

Provide a proper way of running Rails migrations next to Sequent migrations

---

.github/workflows/rspec.yml
CHANGELOG.md
README.md
Rakefile
bin/sequent
docs/docs/building-a-web-application.md
docs/docs/getting-started.md
docs/docs/rails-sequent.md
lib/sequent/generator/template_project/Rakefile
lib/sequent/generator/template_project/spec/spec_helper.rb
lib/sequent/rake/migration_tasks.rb
lib/sequent/support/database.rb
spec/lib/sequent/core/command_spec.rb
spec/lib/sequent/generator/project_spec.rb
spec/spec_helper.rb

Prior to SEQUENT_ENV it relied on RACK_ENV being set mainly due to historic reasons.
In Rake tasks it will use the RAILS_ENV or RACK_ENV as value of SEQUENT_ENV if not set to ease
integration with Rails and frameworks like Sinatra who might use RACK_ENV.

Introduce SEQUENT_ENV

---

docs/docs/concepts/aggregate-root.md

I found a small typo in the AggregateRoot docs.

Fix typo in AggregateRoot docs

---

lib/sequent/test/workflow_helpers.rb

This ensures the after_commit is called in tests.

Handle event within fake transaction

---

CHANGELOG.md
docs/docs/concepts/types.md
lib/sequent/configuration.rb
lib/sequent/core/aggregate_root.rb
lib/sequent/core/command.rb
lib/sequent/core/event.rb
lib/sequent/core/ext/ext.rb
lib/sequent/core/helpers/attribute_support.rb
lib/sequent/core/helpers/default_validators.rb
lib/sequent/core/helpers/param_support.rb
lib/sequent/core/helpers/string_to_value_parsers.rb
lib/sequent/core/helpers/time_validator.rb
lib/sequent/core/helpers/value_validators.rb
lib/sequent/rake/migration_tasks.rb
lib/sequent/test/time_comparison.rb
lib/version.rb
spec/lib/sequent/core/event_spec.rb

[DateTime](https://ruby-doc.org/stdlib-3.1.0/libdoc/date/rdoc/DateTime.html) is considered deprecated. Sequent used `DateTime` for `created_at` of `Event` and `Command`.
This is potentially breaking when one serialized the DateTime in a custom format otherwise this change is fully backward compatible.

Add time as supported type

---

lib/sequent/core/event_store.rb
spec/lib/sequent/core/event_store_spec.rb

When using Rails auto-loading, classes should not be cached.
> Bottom line: do not cache reloadable classes or modules.
Source: https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#reloading-and-stale-objects
The `Sequent::Core::EventStore` caches event classes by default (which is good, because it removes the need for unnecessary slow constant lookups). When using Rails in development we want to disable this, otherwise the `on` blocks registered in objects such as `Sequent::AggregateRoot`s aren't called properly (because the cached (old) event class does not match the one registered in a message handler).
Usage:
```ruby
Sequent.configure do |config|
config.event_store = Sequent::Core::EventStore.new(cache_event_types: !Rails.env.development)
end
```
The …

Add option to not cache event types

---

lib/sequent/core/aggregate_root.rb
lib/sequent/core/aggregate_roots.rb
lib/sequent/core/command.rb
lib/sequent/core/projector.rb
lib/sequent/core/workflow.rb
lib/sequent/test/command_handler_helpers.rb
lib/sequent/util/dry_run.rb
spec/lib/sequent/util/dry_run_spec.rb

Use `ActiveSupport::DescendantsTracker` for fast subclass lookups.
> This module provides an internal implementation to track descendants which is faster than iterating through ObjectSpace.
Also see https://api.rubyonrails.org/classes/ActiveSupport/DescendantsTracker.html.
The following classes have been kept and use `.descendants` for fast lookups internally:
- `Sequent::Core::Commands`
- `Sequent::Core::AggregateRoots`
- `Sequent::Core::Projectors`
- `Sequent::Core::Workflows`

Use `ActiveSupport::DescendantsTracker`

---

lib/sequent/rake/migration_tasks.rb

I continued to receive this error message about wrapping `db:migrate` even after creating a Rake task identical to the one in the error message. Upon investigation, looks like this `ENV` variable is supposed to match the one a few lines above.

Fix: Change db:migrate error message ENV

---

CHANGELOG.md
lib/sequent/migrations/view_schema.rb
spec/lib/sequent/migrations/view_schema_spec.rb

If rake sequent:migrate:offline is called in the same memory space like:
`rake sequent:migrate:online sequent:migrate:offline` it fails.
This scenario is typically done in development environments in which there
is no need for downtime.

Reset the column information on all tables in the plan when migrated online

---

lib/sequent/core/command_service.rb
spec/lib/sequent/core/command_service_spec.rb

`command.valid?` fills the error messages. So wrapping that with `I18n.with_locale` ensures those messages are translated according to the `error_locale_resolver`.
Previously tried to ensure this through a command_middleware, like: 
```ruby
class EnsureCommandErrorLocale
def self.call(command, &block)
I18n.with_locale(Sequent.configuration.error_locale_resolver&.call || I18n.locale) do
command.valid?
end
block.call
end
end
```
But the `command.valid?` called in `Sequent::Core::CommandService#process_command` will override the messages again, reverting it back to the default `I18n.locale`. Hence this PR.

Translate custom errors by error_locale_resolver

---

lib/sequent/migrations/versions.rb
spec/lib/sequent/migrations/view_schema_spec.rb

As it does not have the alter table add column with constraint option

Fix versions migration for postgres 12

---

lib/sequent/migrations/errors.rb
lib/sequent/migrations/planner.rb
lib/sequent/migrations/view_schema.rb
spec/lib/sequent/migrations/view_schema_spec.rb

- Move errors to own file
- Validate plan before starting migration to avoid lingering state

handle invalid migration definition gracefully

---

lib/sequent/core/persistors/replay_optimized_postgres_persistor.rb
spec/lib/sequent/core/persistors/replay_optimized_postgres_persistor_spec.rb

This fixes two problems in the `ReplayOptimizedPostgresPersistor`:
1. The documentation specifies that a default `aggregate_id` index is automatically added. Unfortunately the implementation was broken.
2. The index used the `hash` value of the record keys but did not handle hash collisions at all. So when the hash function collided records could be affected with different keys, causing data corruption.
This PR fixes both issues and (tries to) clean up the code.

Replay optimized postgres persistor fixes

---

lib/sequent.rb
lib/sequent/core/persistors/active_record_persistor.rb
lib/sequent/core/persistors/persistor.rb
lib/sequent/core/persistors/replay_optimized_postgres_persistor.rb
lib/sequent/dry_run/dry_run.rb
lib/sequent/dry_run/read_only_replay_optimized_postgres_persistor.rb
lib/sequent/dry_run/view_schema.rb
lib/sequent/migrations/view_schema.rb
lib/sequent/rake/migration_tasks.rb

This task replays all events for the selected projectors without persisting any results (so it works with a PostgreSQL read-only session).

Add migrate:dryrun task for performance testing of projectors

---

lib/sequent/generator/template_project/db/sequent_schema.rb

while following `docs/docs/getting-started.md` this was causing `bundle exec rake sequent:migrate:online` to fail
```
...
E, [2024-03-01T12:13:29.239226 #44644] ERROR -- : +++++++++++++++ ERROR +++++++++++++++
E, [2024-03-01T12:13:29.239265 #44643] ERROR -- : +++++++++++++++ ERROR +++++++++++++++
E, [2024-03-01T12:13:29.239375 #44644] ERROR -- : PG::UndefinedColumn: ERROR:  column "xact_id" does not exist
LINE 2: ) AND (xact_id IS NULL OR xact_id < 2254234) ORDER BY aggreg...
```

add xact_id to the event_records table when generating a sequent project

---

gemfiles/ar_6_0.gemfile.lock
gemfiles/ar_6_1.gemfile.lock
gemfiles/ar_7_0.gemfile.lock
gemfiles/ar_7_1.gemfile.lock
sequent.gemspec

Similar to what we've seen on https://github.com/zilverline/sequent/issues/268 and https://github.com/zilverline/sequent/pull/374

Relax parser version to allow the latest Rubocop version

---

lib/sequent/core/event_store.rb
lib/sequent/rake/migration_tasks.rb
lib/sequent/test/command_handler_helpers.rb
lib/sequent/util/dry_run.rb
spec/lib/sequent/core/aggregate_repository_spec.rb
spec/lib/sequent/core/aggregate_unique_keys_spec.rb
spec/lib/sequent/core/event_store_spec.rb

Adds a new rake task `sequent:migrate:unique_keys` to load and update all unique keys of an aggregate (optionally filtered by type). This is needed when adding or modifying `unique_key` constraints on an aggregate to ensure all unique keys are present in the `aggregate_unique_keys` table so that uniqueness can be enforced by the database.

Add event store update unique keys method

---

lib/sequent/core/helpers/message_router.rb
spec/lib/sequent/core/helpers/message_router_spec.rb

Avoid building up an entire set of handlers just to check if there are any handlers, but directly query the underlying routes.

Optimize `MessageRouter#matches_message?`

---

db/sequent_8_migration.sql

The columns on the tables expect a UUID, but if you have not updated your old tables to use UUID for `aggregate_id` you would hit errors. (`... is of type uuid but expression is of type character varying`).
AFAIK there is no penalty/problem in case you already are using the UUID, the casting would be a no-op.

Allow you to run the migration to Sequent 8 even if you have not updated `aggregate_id` to be UUID yet.

---

lib/sequent/migrations/functions.rb
lib/sequent/migrations/versions.rb
lib/sequent/migrations/view_schema.rb
spec/lib/sequent/migrations/view_schema_spec.rb

Register the resources affected in the migrations table. Also add some convenience scopes on versions.

Register migrating resources on migration table

---

lib/sequent/core/projector.rb
spec/lib/sequent/core/projector_spec.rb

This will fail fast rather then during a replay.

Fail fast when trying to "persist" a record that isn't supported by a Projector

---

CHANGELOG.md
lib/sequent/migrations/executor.rb
spec/fixtures/db/1/classes.rb
spec/fixtures/db/1/foo_records.sql
spec/fixtures/db/2/foo_records.sql
spec/lib/sequent/migrations/view_schema_spec.rb

Ensure all classes in a STI tree have the correct table_name
and column_information during the migration process.
Although `table_name = 'new_table_name'` internally also resets
all column information we are not sure this also happens
in all supported AR version. So to be sure we call `reset_column_information`
anyway.

Fix view schema migration containing STI projections

---

README.md
gemfiles/ar_7_2.gemfile.lock
gemfiles/ar_8_0.gemfile.lock
lib/sequent/core/event_record.rb
lib/sequent/internal/partitioned_aggregate.rb
lib/sequent/internal/partitioned_event.rb
sequent.gemspec
spec/lib/sequent/internal/partitioned_storage_spec.rb

AR 7.1 is no longer supported by Sequent but some left-over workarounds were still present.

Remove workarounds for activerecord 7.1

---

db/migrate/20250501120000_sequent_track_partition_key_changes.rb
db/migrate/sequent/store_aggregates_v02.sql
db/structure.sql
lib/sequent/internal/internal.rb
lib/sequent/internal/partition_key_change.rb
lib/sequent/rake/migration_tasks.rb
spec/lib/sequent/internal/partitioned_storage_spec.rb

Before the partition key of an aggregate and its events where immediately updated. Unfortunately the view schema migration relies on a stable ordering of aggregates based on `events_partition_key, aggregate_id`. But if this changes while a migration is running the aggregate may not be replayed at all or be replayed multiple times.
With this change the partition key updates are only logged when an aggregate is updated and a separate maintenance task is used to perform the actual updates. This maintenance task can only be run when there is no view schema migration active.

Track event partition key changes for aggregates

---

db/migrate/20250220161400_sequent_register_types.rb
db/migrate/20250509120000_sequent_register_types.rb
db/migrate/sequent/register_types_v01.sql
db/structure.sql
lib/sequent/core/event_store.rb
lib/sequent/rake/migration_tasks.rb

Adds a new Rake task `sequent:register:types` to insert aggregate root, command, and event types into the `*_types` tables. Useful to run after deploying new code so all new types are registered in advance.

Register types rake task

---

db/migrate/20250512135500_sequent_specify_database_insertion_order.rb
db/migrate/sequent/store_aggregates_v03.sql
db/migrate/sequent/store_events_v03.sql
db/migrate/sequent/update_unique_keys_v02.sql
db/structure.sql
spec/lib/sequent/core/event_store_spec.rb

When inserting multiple rows it is important that all inserts happen in a consistent order, otherwise multiple concurrent transactions can deadlock.
Also ensure newly inserted events have a correct sequence number so that a primary key constraint violation is raised when multiple concurrent transactions update the same aggregate, which will result in a Sequent optimistic locking error.

Specify aggregate and event database insertion order

---

lib/sequent/internal/partition_key_change.rb
lib/sequent/rake/migration_tasks.rb
spec/lib/sequent/internal/partitioned_storage_spec.rb

Lock the partition key change and skip if locked, limit statement duration and log number of changes applied.

Make applying partition key changes more robust

---

CHANGELOG.md
db/migrate/20250509133000_sequent_versioned_snapshots.rb
db/migrate/sequent/aggregate_event_type_v02.sql
db/migrate/sequent/aggregates_that_need_snapshots_v01.sql
db/migrate/sequent/aggregates_that_need_snapshots_v02.sql
db/migrate/sequent/delete_snapshots_before_v01.sql
db/migrate/sequent/delete_snapshots_before_v02.sql
db/migrate/sequent/load_event_v02.sql
db/migrate/sequent/load_events_v02.sql
db/migrate/sequent/load_latest_snapshots_v01.sql
db/migrate/sequent/load_latest_snapshots_v02.sql
db/migrate/sequent/select_aggregates_for_snapshotting_v02.sql
db/migrate/sequent/store_aggregates_v03.sql
db/migrate/sequent/store_snapshots_v02.sql
db/structure.sql
docs/docs/concepts/snapshotting.md
lib/sequent/configuration.rb
lib/sequent/core/aggregate_root.rb
lib/sequent/core/aggregate_roots.rb
lib/sequent/core/event.rb
lib/sequent/core/event_store.rb
lib/sequent/core/snapshot_store.rb
lib/sequent/core/stream_record.rb
lib/sequent/rake/migration_tasks.rb
spec/lib/sequent/core/aggregate_repository_spec.rb
spec/lib/sequent/core/aggregate_snapshotter_spec.rb
spec/lib/sequent/core/event_store_spec.rb

To support changing the internals of an aggregate root without having
to throw away the old snapshots the snapshot version can now be
specified. This is needed to be able to support zero-downtime
deployments, where both old and new code run concurrently using the
same event store, but each may require different snapshots.
Example usage:
```
enable_snapshots version: 2
```
The default version is 1.
A hash mapping aggregate types to the supported snapshot version is
passed to every database call that needs it so the snapshot can be
correctly selected. The default implementation queries all descendants
of `AggregateRoot` for the supported snapshot version. This can be
changed using the `aggregate_snapshot_versions` configuration setting.

Aggregate snapshot versioning

---

db/migrate/20250815103000_sequent_add_index_definitions_to_replay_states.rb
db/structure.sql
lib/sequent/core/projector.rb
lib/sequent/core/projectors.rb
lib/sequent/migrations/projectors_replayer.rb
lib/sequent/rake/migration_tasks.rb
spec/lib/sequent/migrations/projectors_replayer_spec.rb

Replaying without indexes speeds up replaying significantly. By default all indexes that are not used for primary key, unique, or exclusion constraints are dropped before replay.
You can use `self.additional_replay_indexes = %w[my_index_name]` to keep additional indexes that your projector needs (maybe to look up rows or validate foreign key constraints).
Before activating the replayed tables the tables are vacuumed or clustered, the dropped indexes are re-created and then all tables and indexes are analyzed.

Drop indexes before replaying, re-create, vacuum, analyze after

---

lib/sequent/rake/migration_tasks.rb

Modifying the view schema migration version requires an exclusive lock on the table which conflicts with (long-running) backup tasks. This can cause the entire system to grind to a halt, even though the table should already be in the right format.

The migration check tasks should only query the version and status
